<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Games.csv" />
	  <None Remove="GamesAllEqual.csv" />
	  <None Remove="GamesByTotalGoalDiff.csv" />
	  <None Remove="GamesEmpty.csv" />
	  <None Remove="GamesMoreGroups.csv" />
	  <None Remove="GamesTwoGroups.csv" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="GamesMoreGroups.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="GamesTwoGroups.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="GamesByTotalGoalDiff.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="GamesEmpty.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="GamesAllEqual.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Games.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="6.4.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
		<PackageReference Include="xunit" Version="2.4.1" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\FussballMeisterschaft\FussballMeisterschaft.csproj" />
	</ItemGroup>
</Project>