<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Game.csv" />
	  <None Remove="chessPieces.csv" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Game.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>