<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Games.csv" />
		<None Remove="Pupils.csv" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Pupils.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>